SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 1(10) TEXT-s01 FOR FIELD p_begda MODIF ID flt.
SELECTION-SCREEN POSITION 33.
PARAMETERS p_begda TYPE datum OBLIGATORY DEFAULT sy-datum MODIF ID flt.
SELECTION-SCREEN COMMENT 52(5) TEXT-s02 FOR FIELD p_endda MODIF ID flt.
PARAMETERS p_endda TYPE datum OBLIGATORY DEFAULT sy-datum MODIF ID flt.
SELECTION-SCREEN END OF LINE.